### ISSUE TITLE
sample config

### ISSUE THREAD

**Issue by frolov32** [pdlove/homebidge-sensibo#1]
Can you add sample config? 
Thanks

**Comment by leoneleone** [comment]
try adding your Sensibo apiKey to config.json

example:
        {
            "platform": "Sensibo",
            "name": "Sensibo",
            "apiKey": " "
        },

**Comment by payote** [comment]
API Keys are available at https://home.sensibo.com/login?next=/me/api

**Comment by pdlove** [comment]
I'll post complete instructions as soon as I've got this plugin working properly. I'm glad to see there is interest.

**Comment by pdlove** [comment]
I've updated the README.md file with setup instructions, sample config and how to get an API key.
@payote Please revoke the key that you gave me for testing before setting this up. I accidentally leaked it into the first commit I did.
